
Notification_Popup_Xpath = "//div[@class='noti_btnwrap']/a"
Sub_Menu_Id = "h_sub_menu"
Section_Text = "WEATHER"
Searchbox_Id = "searchBox"
City_Title_Xpath = "//div[@title='{}']"
City_Temp_Xpath = "//div[@title='{0}']/div/span[@class='{1}']"
City_Weather_Popup_Xpath = "//div[@class='leaflet-popup-content']/div/span"
Temperature_In_Celsius_Class = "tempRedText"
Temperature_In_Fahrenheit_Class = "tempWhiteText"
Top_Nav_Sections_Class = ".topnav_cont a"
Top_Nav_Id = "header2"
Sub_Nav_Id = "subnav"
Pin_Your_City_Class = "message_holder_header"
Reset_To_Default_Id = "icon_holder"
Visible_Cities_To_Pin_Group_Id = "messages"
Visible_City_To_Pin_Class = "message"
Input_Tag = "input"
